<a href="https://colab.research.google.com/github/lilytong0919/NMA-shichimi-rulebreakerhalf-comparing-network/blob/main/parametres_for_motornet_CO_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
!{sys.executable} -m pip install -U pip --quiet
!{sys.executable} -m pip install motornet --quiet
!{sys.executable} -m pip install git+https://github.com/OlivierCodol/MotorNet.git

Collecting git+https://github.com/OlivierCodol/MotorNet.git
  Cloning https://github.com/OlivierCodol/MotorNet.git to /tmp/pip-req-build-ofnk6ykh
  Running command git clone --filter=blob:none --quiet https://github.com/OlivierCodol/MotorNet.git /tmp/pip-req-build-ofnk6ykh
  Resolved https://github.com/OlivierCodol/MotorNet.git to commit ad606747396611689136d9e3a915c80500efeebe
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from motornet==0.3.0) (2.0.2)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from motornet==0.3.0) (2.11.0+cpu)
Requirement already satisfied: gymnasium in /usr/local/lib/python3.12/dist-packages (from motornet==0.3.0) (1.3.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from motornet==0.3.0) (3.10.0)
Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium->motornet==0.3.0) (3.1.2)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium->motornet==0.3.0) (4.16.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from gymnasium->motornet==0.3.0) (0.0.6)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->motornet==0.3.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->motornet==0.3.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->motornet==0.3.0) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->motornet==0.3.0) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->motornet==0.3.0) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->motornet==0.3.0) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->motornet==0.3.0) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->motornet==0.3.0) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->motornet==0.3.0) (1.17.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->motornet==0.3.0) (3.29.7)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch->motornet==0.3.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->motornet==0.3.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->motornet==0.3.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->motornet==0.3.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->motornet==0.3.0) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->motornet==0.3.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->motornet==0.3.0) (3.0.3)

In [2]:
!pip install --no-cache-dir --force-reinstall --no-deps \
    git+https://github.com/lilytong0919/NMA-shichimi-rulebreakerhalf-comparing-network.git
!pip install pynapple --quiet

Collecting git+https://github.com/lilytong0919/NMA-shichimi-rulebreakerhalf-comparing-network.git
  Cloning https://github.com/lilytong0919/NMA-shichimi-rulebreakerhalf-comparing-network.git to /tmp/pip-req-build-qm0s513j
  Running command git clone --filter=blob:none --quiet https://github.com/lilytong0919/NMA-shichimi-rulebreakerhalf-comparing-network.git /tmp/pip-req-build-qm0s513j
  Resolved https://github.com/lilytong0919/NMA-shichimi-rulebreakerhalf-comparing-network.git to commit 0d0e1cad9b77950d0333b4110856aa9a0ac792b8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: monkeypaw
  Building wheel for monkeypaw (pyproject.toml) ... done
  Created wheel for monkeypaw: filename=monkeypaw-0.1.0-py3-none-any.whl size=6092 sha256=9ee3c52921cf76ceebc4e5da2dba9422319ce69f8958c9de6546f1e3b154d038
  Stored in directory: /tmp/pip-ephem-wheel-cache-n73l80gf/wheels/c5/4d/e0/f4cdde16d1079b6e82b4e94fb243e7e447475b8f6c6ad15d9c
Successfully built monkeypaw
Installing collected packages: monkeypaw
  Attempting uninstall: monkeypaw
    Found existing installation: monkeypaw 0.1.0
    Uninstalling monkeypaw-0.1.0:
      Successfully uninstalled monkeypaw-0.1.0
Successfully installed monkeypaw-0.1.0

In [3]:
!pip install dandi --quiet

In [4]:
!python3 -m pip install pynapple --quiet

In [5]:

from google.colab import drive
import monkeypaw.io as mpio
import pandas as pd
from dandi.download import download as dandi_download
import os
import pynapple as nap
import numpy as np


# 2. Mount Google Drive for persistent storage
drive.mount('/content/drive')

# 3. Define a dedicated folder inside your Google Drive
drive_data_dir = "/content/drive/MyDrive/Dandi_Datasets/data"
os.makedirs(drive_data_dir, exist_ok=True)

filenames = [
    "sub-Dataset-3-Animals-1-to-4",
    "sub-Dataset-4-Animal-2-sess-1-to-7",
    "sub-Dataset-4-Animal-2-sess-8-to-12",
    "sub-Dataset-4-Animal-3-sess-1-to-6",
    "sub-Dataset-4-Animal-3-sess-7-to-11",
    "sub-Dataset-5-Animal-1",
    "sub-Dataset-5-Animals-2-ses-1-to-19",
    "sub-Dataset-5-Animals-2-ses-20-to-39",
    "sub-Dataset-5-Animals-2-ses-40-to-51",
    "sub-Dataset-5-Animals-3&4"
]

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
url_base = 'https://dandiarchive.org/dandiset/001057/draft/files?location='

# 4. Check if the directory already has files to avoid starting the dandi client
if os.path.exists(drive_data_dir) and len(os.listdir(drive_data_dir)) >= len(filenames):
    print("✨ All files are already saved in Google Drive! Skipping download loop.")
else:
    print("⏳ Files missing. Running DANDI download loop straight to Google Drive...")
    for filename in filenames:
        url = url_base + filename
        # Downloads directly into your persistent Drive folder
        dandi_download(
            [url],
            output_dir=drive_data_dir,
            existing="skip"
        )
    print("✅ Download complete and saved to Google Drive.")

✨ All files are already saved in Google Drive! Skipping download loop.

**Shared keys between 3 dataset are also:** (different spelling)
- 'EventTarget_Onset' (dataset 3 and 4), 'EventTarget_onset'(dataset 5)
- 'target_dir'(dataset 3 and 4), 'targets_dir'(dataset 5)

Shared keys only between dataset 4 and 5:
- 'cursor_vel_y',  'cursor_vel_x', 'cursor_pos_y', 'cursor_pos_x',  'cursor_acc_y',  'cursor_acc_x'

**Also between dataset 4 and 5:** (different spelling)
- 'target_ID' (dataset 4), 'Target_ID'(dataset 5)

In [7]:
dat1 = mpio.nap_load_data(os.path.join(drive_data_dir,filenames[0],filenames[0]+'.nwb'))

Original keys: ['spikes_counts', 'trial_id', 'session', 'datasetID', 'animal', 'result', 'EventTarget_Onset', 'EventMovement_start', 'EventGo_cue', 'target_dir', 'hand_vel_y', 'hand_vel_x', 'date', 'brain_region']

In [8]:
dat1

sub-Dataset-3-Animals-1-to-4
┍━━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━━━┑
│ Keys                │ Type     │
┝━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━━━┥
│ spikes_counts       │ TsdFrame │
│ trial_id            │ Tsd      │
│ session             │ Tsd      │
│ datasetID           │ Tsd      │
│ animal              │ Tsd      │
│ result              │ Tsd      │
│ EventTarget_Onset   │ Tsd      │
│ EventMovement_start │ Tsd      │
│ EventGo_cue         │ Tsd      │
│ target_dir          │ Tsd      │
│ hand_vel_y          │ Tsd      │
│ hand_vel_x          │ Tsd      │
│ date                │ Tsd      │
│ brain_region        │ Tsd      │
┕━━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━━━┙

In [9]:
dat1_info = mpio.get_info(dat1)
dat1_info

Time (s)              trial_id    animal    datasetID    session  brain_region
------------------  ----------  --------  -----------  ---------  --------------
0.0                          1         1            3          1  M1
0.03                         1         1            3          1  M1
0.06                         1         1            3          1  M1
0.09                         1         1            3          1  M1
0.12                         1         1            3          1  M1
0.15                         1         1            3          1  M1
0.18                         1         1            3          1  M1
...
32235.059999999998         465         3            3          3  Area2
32235.089999999997         465         3            3          3  Area2
32235.12                   465         3            3          3  Area2
32235.149999999998         465         3            3          3  Area2
32235.179999999997         465         3            3          3  Area2
32235.21                   465         3            3          3  Area2
32235.239999999998         465         3            3          3  Area2
dtype: object, shape: (1074509, 5)

In [10]:
dat1_behav = mpio.get_behav(dat1)
dat1_behav

Time (s)            EventGo_cue    EventTarget_Onset      target_ID    target_dir  result    ...
------------------  -------------  -------------------  -----------  ------------  --------  -----
0.0                 False          False                        nan       0        R         ...
0.03                False          False                        nan       0        R         ...
0.06                False          False                        nan       0        R         ...
0.09                False          False                        nan       0        R         ...
0.12                False          False                        nan       0        R         ...
0.15                False          False                        nan       0        R         ...
0.18                False          False                        nan       0        R         ...
...                                                                                          ...
32235.059999999998  False          False                        nan       3.14159  R         ...
32235.089999999997  False          False                        nan       3.14159  R         ...
32235.12            False          False                        nan       3.14159  R         ...
32235.149999999998  False          False                        nan       3.14159  R         ...
32235.179999999997  False          False                        nan       3.14159  R         ...
32235.21            False          False                        nan       3.14159  R         ...
32235.239999999998  False          False                        nan       3.14159  R         ...
dtype: object, shape: (1074509, 11)

In [11]:
merged_dat1_df = pd.merge(dat1_info.as_dataframe(), dat1_behav.as_dataframe(), left_index=True, right_index=True, how='outer', suffixes=('_info', '_behav'))

display(merged_dat1_df.head())

,trial_id,animal,datasetID,session,brain_region,EventGo_cue,EventTarget_Onset,target_ID,target_dir,result,cursor_pos_x,cursor_pos_y,cursor_vel_x,cursor_vel_y,cursor_acc_x,cursor_acc_y
0.00,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
0.03,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
0.06,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
0.09,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
0.12,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
merged_dat1_df = merged_dat1_df.reset_index()
merged_dat1_df = merged_dat1_df.rename(columns={'index': 'time_s'})
display(merged_dat1_df)

,time_s,trial_id,animal,datasetID,session,brain_region,EventGo_cue,EventTarget_Onset,target_ID,target_dir,result,cursor_pos_x,cursor_pos_y,cursor_vel_x,cursor_vel_y,cursor_acc_x,cursor_acc_y
0,0.00,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
1,0.03,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
2,0.06,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
3,0.09,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
4,0.12,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1074504,32235.12,465,3,3,3,Area2,False,False,NaN,3.141593,R,NaN,NaN,NaN,NaN,NaN,NaN
1074505,32235.15,465,3,3,3,Area2,False,False,NaN,3.141593,R,NaN,NaN,NaN,NaN,NaN,NaN
1074506,32235.18,465,3,3,3,Area2,False,False,NaN,3.141593,R,NaN,NaN,NaN,NaN,NaN,NaN
1074507,32235.21,465,3,3,3,Area2,False,False,NaN,3.141593,R,NaN,NaN,NaN,NaN,NaN,NaN
1074508,32235.24,465,3,3,3,Area2,False,False,NaN,3.141593,R,NaN,NaN,NaN,NaN,NaN,NaN

**select animal**

In [13]:
anix_dat1_df = merged_dat1_df[merged_dat1_df['animal']==1]
anix_dat1_df

,time_s,trial_id,animal,datasetID,session,brain_region,EventGo_cue,EventTarget_Onset,target_ID,target_dir,result,cursor_pos_x,cursor_pos_y,cursor_vel_x,cursor_vel_y,cursor_acc_x,cursor_acc_y
0,0.00,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
1,0.03,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
2,0.06,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
3,0.09,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
4,0.12,1,1,3,1,M1,False,False,NaN,0.0,R,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484334,14530.02,286,1,3,10,M1,False,False,NaN,3.141593,R,NaN,NaN,NaN,NaN,NaN,NaN
484335,14530.05,286,1,3,10,M1,False,False,NaN,3.141593,R,NaN,NaN,NaN,NaN,NaN,NaN
484336,14530.08,286,1,3,10,M1,False,False,NaN,3.141593,R,NaN,NaN,NaN,NaN,NaN,NaN
484337,14530.11,286,1,3,10,M1,False,False,NaN,3.141593,R,NaN,NaN,NaN,NaN,NaN,NaN
484338,14530.14,286,1,3,10,M1,False,False,NaN,3.141593,R,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
np.max(anix_dat1_df['trial_id'])

1038

In [15]:
print('Unique values for each column in df_ani2_nospc:')
for col in anix_dat1_df.columns:
    unique_vals = anix_dat1_df[col].unique()
    print(f"Column '{col}': {unique_vals}")
    print(f"Number of unique values in '{col}': {len(unique_vals)}")
    print('-' * 30)

Unique values for each column in df_ani2_nospc:
Column 'time_s': [0.000000e+00 3.000000e-02 6.000000e-02 ... 1.453008e+04 1.453011e+04
 1.453014e+04]
Number of unique values in 'time_s': 484339
------------------------------
Column 'trial_id': [1 2 3 ... 1036 1037 1038]
Number of unique values in 'trial_id': 1038
------------------------------
Column 'animal': [1]
Number of unique values in 'animal': 1
------------------------------
Column 'datasetID': [3]
Number of unique values in 'datasetID': 1
------------------------------
Column 'session': [1 2 3 4 5 6 7 8 9 10]
Number of unique values in 'session': 10
------------------------------
Column 'brain_region': ['M1']
Number of unique values in 'brain_region': 1
------------------------------
Column 'EventGo_cue': [False True]
Number of unique values in 'EventGo_cue': 2
------------------------------
Column 'EventTarget_Onset': [False True]
Number of unique values in 'EventTarget_Onset': 2
------------------------------
Column 'target_ID': [nan]
Number of unique values in 'target_ID': 1
------------------------------
Column 'target_dir': [0.0 3.141592653589793 4.71238898038469 3.9269908169872414
 1.5707963267948966 2.356194490192345 0.7853981633974483 5.497787143782138]
Number of unique values in 'target_dir': 8
------------------------------
Column 'result': ['R']
Number of unique values in 'result': 1
------------------------------
Column 'cursor_pos_x': [nan]
Number of unique values in 'cursor_pos_x': 1
------------------------------
Column 'cursor_pos_y': [nan]
Number of unique values in 'cursor_pos_y': 1
------------------------------
Column 'cursor_vel_x': [nan]
Number of unique values in 'cursor_vel_x': 1
------------------------------
Column 'cursor_vel_y': [nan]
Number of unique values in 'cursor_vel_y': 1
------------------------------
Column 'cursor_acc_x': [nan]
Number of unique values in 'cursor_acc_x': 1
------------------------------
Column 'cursor_acc_y': [nan]
Number of unique values in 'cursor_acc_y': 1
------------------------------

In [16]:
print('max cursor_pos_x (mm): ', anix_dat1_df['cursor_pos_x'].max())
print('min cursor_pos_x (mm): ', anix_dat1_df['cursor_pos_x'].min())

max cursor_pos_x (mm):  nan
min cursor_pos_x (mm):  nan

In [17]:
print('max cursor_pos_y (mm): ', anix_dat1_df['cursor_pos_y'].max())
print('min cursor_pos_y (mm): ', anix_dat1_df['cursor_pos_y'].min())

max cursor_pos_y (mm):  nan
min cursor_pos_y (mm):  nan

**catch_trial_perc**

In [18]:
# First, determine for each trial if it is a catch trial (where EventGo_cue is False throughout the trial)
# or if the result for that trial is 'A' (Aborted).

is_catch_trial = anix_dat1_df.groupby(['animal', 'session', 'trial_id']).apply(
    lambda group: (not group['EventGo_cue'].any()) or (group['result'] == 'A').any() or (group['result'] == 'I').any() or (group['result'] == 'F').any()
)

# Convert the result to a DataFrame
df_trials_status = is_catch_trial.reset_index(name='is_catch')

# Count the number of catch trials per animal and session
catch_trial_counts = df_trials_status[df_trials_status['is_catch']].groupby(['animal', 'session']).size().reset_index(name='num_catch_trials')

# Count the total number of trials per animal and session
total_trial_counts = df_trials_status.groupby(['animal', 'session']).size().reset_index(name='total_trials')

# Merge the counts and calculate the percentage
df_catch_trials = pd.merge(total_trial_counts, catch_trial_counts, on=['animal', 'session'], how='left').fillna(0)
df_catch_trials['catch_trial_perc'] = (df_catch_trials['num_catch_trials'] / df_catch_trials['total_trials']) * 100

# Display the results
display(df_catch_trials)

/tmp/ipykernel_20342/3843257766.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  is_catch_trial = anix_dat1_df.groupby(['animal', 'session', 'trial_id']).apply(

   animal  session  total_trials  num_catch_trials  catch_trial_perc
0       1        1          1038               0.0               0.0
1       1        2          1026               0.0               0.0
2       1        3           179               0.0               0.0
3       1        4           178               0.0               0.0
4       1        5           208               0.0               0.0
5       1        6           202               0.0               0.0
6       1        7           209               0.0               0.0
7       1        8           168               0.0               0.0
8       1        9           740               0.0               0.0
9       1       10           286               0.0               0.0

In [19]:
# Display the trial IDs where 'is_catch_trial' is True, in other words no go cue during that trial
catch_trial_ids = is_catch_trial[is_catch_trial == True]
display(catch_trial_ids)

Series([], dtype: bool)

In [20]:
df_catch_trials['catch_trial_perc'].mean()

np.float64(0.0)

### Calculating **`reaching_distance`** and **`start_position`** from `df`

Based on the `motornet_tf.tasks.CentreOutReach` documentation, `reaching_distance` is the distance of the center-out reach, and `start_position` is the origin of the reach. We can derive suitable values for these parameters from the `df2` data using the `cursor_pos_x`, `cursor_pos_y`, and `EventTarget_Onset` columns.

In [21]:
import numpy as np


# Initialize lists to store calculated reaching distances and start positions for each trial
trial_reaching_distances = []
trial_start_positions = []

# Group df2 by animal, session, and trial_id
grouped_df = anix_dat1_df.groupby(['animal', 'session', 'trial_id'])

for (animal, session, trial_id), trial_df in grouped_df:
    # Find the row(s) where EventTarget_Onset is True
    target_onset_rows = trial_df[trial_df['EventTarget_Onset'] == True]

    if not target_onset_rows.empty:
        # Take the first instance of EventTarget_Onset as the start of the reach
        target_onset_row = target_onset_rows.iloc[0]

        # Convert cursor position from mm to meters (1000 mm = 1 m)
        start_x_m = target_onset_row['cursor_pos_x'] /1000
        start_y_m = target_onset_row['cursor_pos_y'] / 1000
        # if cursor position is in metres
        #start_x_m = target_onset_row['cursor_pos_x']
        #start_y_m = target_onset_row['cursor_pos_y']
        trial_start_positions.append((start_x_m, start_y_m))

        # Filter the DataFrame to include only points from (and after) the target onset time
        movement_df = trial_df[trial_df['time_s'] >= target_onset_row['time_s']].copy()

        # Calculate Euclidean distance from the start position for all points in movement_df
        # Only consider points where cursor position data is not NaN
        valid_movement_df = movement_df.dropna(subset=['cursor_pos_x', 'cursor_pos_y'])

        if not valid_movement_df.empty:
            # Convert cursor positions in valid_movement_df from mm to meters before calculating distance
            distances = np.sqrt(
                ((valid_movement_df['cursor_pos_x'] / 1000) - start_x_m)**2 +
                ((valid_movement_df['cursor_pos_y'] / 1000) - start_y_m)**2
            )
           # distances = np.sqrt(
            #    ((valid_movement_df['cursor_pos_x']) - start_x_m)**2 +
             #   ((valid_movement_df['cursor_pos_y']) - start_y_m)**2
            #)

            if not distances.empty:
                max_distance = distances.max()
                trial_reaching_distances.append(max_distance)

# Calculate the average reaching distance
if trial_reaching_distances:
    mean_reaching_distance = np.mean(trial_reaching_distances)
    print(f"\nSuggested 'reaching_distance': {mean_reaching_distance:.4f} meters")
else:
    print("\nCould not calculate 'reaching_distance'. No valid trials found with 'EventTarget_Onset' and cursor data.")

# Calculate the average start position
if trial_start_positions:
    avg_start_x_m = np.mean([pos[0] for pos in trial_start_positions])
    avg_start_y_m = np.mean([pos[1] for pos in trial_start_positions])
    print(f"Suggested 'start_position': [{avg_start_x_m:.4f}, {avg_start_y_m:.4f}] meters")
else:
    print("Could not determine 'start_position'. No valid trials found with 'EventTarget_Onset' and cursor data.")

Could not calculate 'reaching_distance'. No valid trials found with 'EventTarget_Onset' and cursor data.
Suggested 'start_position': [nan, nan] meters

**gocue_range**

In [22]:
# Group by trial and find the start time of each trial
trial_start_times = anix_dat1_df.groupby(['animal', 'session', 'trial_id'])['time_s'].min()

# For each trial that has an EventGo_cue, find the time of its first occurrence
go_cue_onsets = anix_dat1_df[anix_dat1_df['EventGo_cue'] == True].groupby(['animal', 'session', 'trial_id'])['time_s'].min()

# Calculate the relative go cue onset times for trials that have a go cue.
# We use reindex to ensure proper alignment and .dropna() to exclude catch trials (where go_cue_onsets would be NaN).
relative_go_cue_onsets = (go_cue_onsets - trial_start_times).dropna()

# Determine the overall go_cue_range from these relative onset times
if not relative_go_cue_onsets.empty:
    go_cue_range_min = round(relative_go_cue_onsets.min(),2)
    go_cue_range_max = round(relative_go_cue_onsets.max(),2)
    go_cue_range = [go_cue_range_min, go_cue_range_max]
    print(f"Calculated `go_cue_range` from df1 (relative to the start of the trial): {go_cue_range} seconds")
else:
    print("No trials with 'EventGo_cue' found to calculate `go_cue_range`.")
    go_cue_range = None # Assign None if no go cues are found

Calculated `go_cue_range` from df1 (relative to the start of the trial): [0.57, 46.89] seconds

In [23]:
# For each trial that has an EventTarget_Onset, find the time of its first occurrence
target_onsets = anix_dat1_df[anix_dat1_df['EventTarget_Onset'] == True].groupby(['animal', 'session', 'trial_id'])['time_s'].min()

# For each trial that has an EventGo_cue, find the time of its first occurrence
go_cue_onsets = anix_dat1_df[anix_dat1_df['EventGo_cue'] == True].groupby(['animal', 'session', 'trial_id'])['time_s'].min()

# Calculate the relative go cue onset times for trials that have both a target onset and a go cue.
# This measures the time from target onset to go cue.
relative_go_cue_onsets = (go_cue_onsets - target_onsets).dropna()

# Determine the overall go_cue_range from these relative onset times
if not relative_go_cue_onsets.empty:
    go_cue_range_min = round(relative_go_cue_onsets.min(), 2)
    go_cue_range_max = round(relative_go_cue_onsets.max(), 2)
    go_cue_range = [go_cue_range_min, go_cue_range_max]
    print(f"Calculated `go_cue_range` from df1 (relative to EventTarget_Onset): {go_cue_range} seconds")
else:
    print("No trials with both 'EventTarget_Onset' and 'EventGo_cue' found to calculate `go_cue_range`.")
    go_cue_range = None # Assign None if no go cues are found

Calculated `go_cue_range` from df1 (relative to EventTarget_Onset): [0.0, 2.76] seconds

In [24]:
relative_go_cue_onsets

animal  session  trial_id
1       1        1           0.00
                 2           0.00
                 3           0.00
                 4           0.00
                 5           0.00
                             ...
        10       282         1.14
                 283         1.17
                 284         1.02
                 285         0.78
                 286         1.14
Name: time_s, Length: 4234, dtype: float64